In [3]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
import os

print(os.listdir("/content"))

['.config', 'adult.names', 'adult.test', 'adult.data', 'old.adult.names', 'Index', 'sample_data']

In [5]:
df = pd.read_csv("/content/adult.data")

df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [6]:
# Check the number of rows and columns
print("Rows and columns:", df.shape)

# View column names
print("\nColumn names:")
print(df.columns.tolist())

# Check data types and non-null values
print("\nDataset information:")
df.info()

# Check the first five rows
display(df.head())

Rows and columns: (32560, 15)

Column names:
['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married', ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0', ' 40', ' United-States', ' <=50K']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   39              32560 non-null  int64
 1    State-gov      32560 non-null  object
 2    77516          32560 non-null  int64
 3    Bachelors      32560 non-null  object
 4    13             32560 non-null  int64
 5    Never-married  32560 non-null  object
 6    Adm-clerical   32560 non-null  object
 7    Not-in-family  32560 non-null  object
 8    White          32560 non-null  object
 9    Male           32560 non-null  object
 10   2174           32560 non-null  int64
 11   0              32560 non-null  int64
 12   40             32560 non-null  int64
 13   United-States  32560 non-null  object
 14   <=50K          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [8]:
#Step 4: Identify missing values
print(df.isnull().sum())

39                0
 State-gov        0
 77516            0
 Bachelors        0
 13               0
 Never-married    0
 Adm-clerical     0
 Not-in-family    0
 White            0
 Male             0
 2174             0
 0                0
 40               0
 United-States    0
 <=50K            0
dtype: int64

In [9]:
# Count '?' values in each column
for col in df.select_dtypes(include="object").columns:
    count = (df[col].astype(str).str.strip() == "?").sum()
    if count > 0:
        print(col, ":", count, "unknown values")

 State-gov : 1836 unknown values
 Adm-clerical : 1843 unknown values
 United-States : 583 unknown values

In [ ]:
#Step 5: Check duplicate rows
print("Total duplicate rows:", df.duplicated().sum())

In [10]:
#Step 6: Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   39              32560 non-null  int64
 1    State-gov      32560 non-null  object
 2    77516          32560 non-null  int64
 3    Bachelors      32560 non-null  object
 4    13             32560 non-null  int64
 5    Never-married  32560 non-null  object
 6    Adm-clerical   32560 non-null  object
 7    Not-in-family  32560 non-null  object
 8    White          32560 non-null  object
 9    Male           32560 non-null  object
 10   2174           32560 non-null  int64
 11   0              32560 non-null  int64
 12   40             32560 non-null  int64
 13   United-States  32560 non-null  object
 14   <=50K          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [11]:
#Step 7: Check inconsistent values
for col in df.select_dtypes(include="object").columns:
    print(f"\nColumn: {col}")
    print(df[col].value_counts().head(10))

Column:  State-gov
 State-gov
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1297
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

Column:  Bachelors
 Bachelors
HS-grad         10501
Some-college     7291
Bachelors        5354
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
Name: count, dtype: int64

Column:  Never-married
 Never-married
Married-civ-spouse       14976
Never-married            10682
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

Column:  Adm-clerical
 Adm-clerical
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3769
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Name: count, dtype: int64

Column:  Not-in-family
 Not-in-family
Husband           13193
Not-in-family      8304
Own-child          5068
Unmarried          3446
Wife               1568
Other-relative      981
Name: count, dtype: int64

Column:  White
 White
White                 27815
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

Column:  Male
 Male
Male      21789
Female    10771
Name: count, dtype: int64

Column:  United-States
 United-States
United-States    29169
Mexico             643
?                  583
Philippines        198
Germany            137
Canada             121
Puerto-Rico        114
El-Salvador        106
India              100
Cuba                95
Name: count, dtype: int64

Column:  <=50K
 <=50K
<=50K    24719
>50K      7841
Name: count, dtype: int64

In [12]:
#Step 8: Record the original dataset statistics
print("Original rows:", df.shape[0])
print("Original columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Original rows: 32560
Original columns: 15
Missing values: 0
Duplicate rows: 24

In [13]:
#Step 9: Handle missing values represented by ?
# Count '?' values in each column
for col in df.select_dtypes(include="object").columns:
    count = (df[col].astype(str).str.strip() == "?").sum()

    if count > 0:
        print(f"{col}: {count} missing values")

 State-gov: 1836 missing values
 Adm-clerical: 1843 missing values
 United-States: 583 missing values

In [14]:
#Step 10: Remove extra spaces
# Remove leading and trailing spaces from text columns
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

print("Extra spaces removed.")

Extra spaces removed.

In [15]:
#Step 11: Convert ? into proper missing values
# Replace '?' with NaN
df = df.replace(r'^\s*\?\s*$', np.nan, regex=True)

# Check missing values again
print(df.isnull().sum()[df.isnull().sum() > 0])

State-gov        1836
Adm-clerical     1843
United-States     583
dtype: int64

In [16]:
#Step 12: Check missing values again
# Count missing values in each column
print(df.isnull().sum())

# Total missing values
print("\nTotal missing values:", df.isnull().sum().sum())

39                   0
 State-gov        1836
 77516               0
 Bachelors           0
 13                  0
 Never-married       0
 Adm-clerical     1843
 Not-in-family       0
 White               0
 Male                0
 2174                0
 0                   0
 40                  0
 United-States     583
 <=50K               0
dtype: int64

Total missing values: 4262

In [17]:
#Step 13: Handle missing values
# Find categorical columns
categorical_cols = df.select_dtypes(
    include=["object", "category"]
).columns

# Fill missing categorical values with the mode
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value)

print("Missing values after imputation:",
      df.isnull().sum().sum())

Missing values after imputation: 0

In [18]:
#Step 14: Inspect and remove duplicate rows
print("Duplicates before cleaning:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after cleaning:", df.duplicated().sum())
print("Dataset shape after removing duplicates:", df.shape)

Duplicates before cleaning: 24
Duplicates after cleaning: 0
Dataset shape after removing duplicates: (32536, 15)

In [20]:
#Step 15: Validate the cleaned dataset
print("Final rows:", df.shape[0])
print("Final columns:", df.shape[1])
print("Total missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

display(df.head())

Final rows: 32536
Final columns: 15
Total missing values: 0
Duplicate rows: 0

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [25]:
print("CLEANED DATASET REPORT")
print("----------------------")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

CLEANED DATASET REPORT
----------------------
Rows: 32536
Columns: 15
Missing values: 0
Duplicate rows: 0

In [26]:
df.to_csv(
    "/content/cleaned_adult_income.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!